// Package generate renders internal/routersource/source.go, the one file
// main.go's import never varies from. cmd/genrouter calls it instead of a
// shell heredoc so the drop-in's shape is guaranteed to be valid, gofmt'd
// Go source regardless of what's being composed into it.
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// Mount composes one router package's routes into the deployment's default
// router, under a URL path prefix.
type Mount struct {
	// Package is the import path of a package exposing
	// NewRouter() http.Handler, e.g.
	// "github.com/dash-xd/github-device-auth/router".
	Package string

	// Prefix is the URL path this package's router is mounted at, e.g.
	// "/auth". Requests under it are stripped of the prefix before
	// reaching the mounted router.
	Prefix string
}

// Source selects what's composed onto the default router for this
// deployment. The default route (GET /healthz) is always present;
// Mounts adds routers from other packages alongside it, each under its
// own path prefix.
type Source struct {
	Mounts []Mount
}

var sourceTemplate = template.Must(template.New("source.go").Funcs(template.FuncMap{
	"trimSuffix": strings.TrimSuffix,
}).Parse(`// Code generated by cmd/genrouter. DO NOT EDIT.
//
// This is a build-time drop-in: cmd/genrouter regenerates this file to
// compose in whichever router packages should back this deployment.
// main.go's import of this package never changes; only the body below
// does. The default route (GET /healthz) is always present; run
// ` + "`go run ./cmd/genrouter -mount=<package>=<prefix>`" + ` (repeatable) to
// compose additional routers in, or with no flags to reset to just the
// default route (see the .github/actions/router action for the CI path).
package routersource

import (
	"net/http"
{{- if .Mounts}}

{{- range $i, $m := .Mounts}}
	mount{{$i}} "{{$m.Package}}"
{{- end}}
{{- end}}
)

// NewRouter returns the router for this deployment: the default route
// plus anything composed in via cmd/genrouter.
func NewRouter() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	})
{{range $i, $m := .Mounts}}
	mux.Handle("{{$m.Prefix}}/", http.StripPrefix("{{trimSuffix $m.Prefix "/"}}", mount{{$i}}.NewRouter()))
{{- end}}

	return mux
}
`))

// Generate renders source.go's contents for s, gofmt'd and ready to write
// to disk.
func Generate(s Source) ([]byte, error) {
	var buf bytes.Buffer
	if err := sourceTemplate.Execute(&buf, s); err != nil {
		return nil, fmt.Errorf("render source.go template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt rendered source.go: %w", err)
	}

	return formatted, nil
}
