// Package generate renders internal/routersource/source.go, the one file
// main.go's import never varies from. cmd/genrouter calls it instead of a
// shell heredoc so the drop-in's shape is guaranteed to be valid, gofmt'd
// Go source regardless of what's being pointed at.
package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

// Source selects which router backs a deployment.
type Source struct {
	// RouterPackage is the import path of a package exposing
	// NewRouter() http.Handler, e.g.
	// "github.com/dash-xd/github-device-auth/router". Empty selects the
	// default: a minimal stdlib http.ServeMux with a health check and
	// nothing else, so the repo builds and deploys standalone with no
	// external router dependency.
	RouterPackage string
}

var sourceTemplate = template.Must(template.New("source.go").Parse(`// Code generated by cmd/genrouter. DO NOT EDIT.
package routersource

import (
	"net/http"
{{- if .RouterPackage}}

	router "{{.RouterPackage}}"
{{- end}}
)

// NewRouter returns the router for this deployment.
func NewRouter() http.Handler {
{{- if .RouterPackage}}
	return router.NewRouter()
{{- else}}
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	})

	return mux
{{- end}}
}
`))

// Generate renders source.go's contents for s, gofmt'd and ready to write
// to disk.
func Generate(s Source) ([]byte, error) {
	var buf bytes.Buffer
	if err := sourceTemplate.Execute(&buf, s); err != nil {
		return nil, fmt.Errorf("render source.go template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt rendered source.go: %w", err)
	}

	return formatted, nil
}
