// Code generated by cmd/genrouter. DO NOT EDIT.
//
// This is a build-time drop-in: cmd/genrouter regenerates this file to
// compose in whichever router packages should back this deployment.
// main.go's import of this package never changes; only the body below
// does. The default route (GET /healthz) is always present; run
// `go run ./cmd/genrouter -mount=<package>=<prefix>` (repeatable) to
// compose additional routers in, or with no flags to reset to just the
// default route (see the .github/actions/router action for the CI path).
package routersource

import (
	"net/http"
)

// NewRouter returns the router for this deployment: the default route
// plus anything composed in via cmd/genrouter.
func NewRouter() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	})

	return mux
}
